on:
  schedule:
    # 2:20 past midnight UTC
    - cron: "20 2 * * *"

name: Security audit
jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2

      - name: Run audit check
        uses: actions-rs/audit-check@35b7b53b1e25b55642157ac01b4adceb5b9ebef3 # v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
