on:
  push:
    branches:
      - "master"
  pull_request:

name: "Build feature combinations"

jobs:
  feature-powerset:
    name: "Build ${{ matrix.package }} features"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        package:
          - "starknet-curve"
          - "starknet-crypto"
          - "starknet-core"
          - "starknet-providers"
          - "starknet-signers"
          - "starknet-accounts"
          - "starknet-contract"
          - "starknet-macros"
          - "starknet"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26" # v3

      - name: "Setup stable toolchain"
        uses: "actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af" # v1
        with:
          toolchain: "stable"
          profile: "minimal"
          override: true

      - name: "Use Rust cache"
        uses: "Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32" # v2
        with:
          cache-on-failure: true

      - name: "Install cargo-hack"
        run: |
          cargo install --locked cargo-hack

      - name: "Build all feature combinations"
        run: |
          cargo hack build --package ${{ matrix.package }} --feature-powerset

  cpp-integration:
    name: "Build C++ integration example"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26" # v3

      - name: "Setup stable toolchain"
        uses: "actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af" # v1
        with:
          toolchain: "stable"
          profile: "minimal"
          override: true

      - name: "Build starknet-cxx example"
        run: |
          cd ./examples/starknet-cxx
          mkdir build
          cd ./build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make

      - name: "Run starknet-cxx example"
        run: |
          ./examples/starknet-cxx/build/main
